---

nginx_revproxy_sites:                                         # List of sites to reverse proxy
  docampoparavoce.com.br:                                                # Domain name
    client_max_body_size: "256M"
    proxy_read_timeout: "360"
    domains:                                                  # List of server_name aliases
      - docampoparavoce.com.br 
    upstreams:                                                # List of Upstreams
      - {backend_address: 139.144.132.52, backend_port: 80}
